import httpx
from .logger import log as log
from typing import Any, ClassVar, Dict, List, Optional, Union

JSON = Dict[str, Any]
Params = Dict[str, Union[str, float]]
Geometry = List[float]
TIMEOUT: float = ...

def log_request(request: httpx.Request) -> None: ...
def log_response(response: httpx.Response) -> None: ...
def process_response(response: JSON) -> Geometry: ...

class Visicom:
    BASE_URL: ClassVar[str]
    token: str
    client: httpx.Client
    def ensure_context_created(self) -> None: ...
    def fetch(self, endpoint: str, params: Optional[Params] = ...) -> httpx.Response: ...
    def geocode(self, address: str, limit: bool = ...) -> Union[JSON, Geometry, List]: ...
    def __init__(self, token: str) -> None: ...
